apiVersion: v1
kind: Service
metadata:
    name: "rhynelabkube1-d557"
    labels:
        app: "rhynelabkube1-d557"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "rhynelabkube1-d557"